version: '3.5'
######################### NETWORKS #########################
networks:
  elastic-net:
    driver: bridge
    name: elastic-net

services:
   elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
     restart: always
     ports:
       - 9200:9200
       - 9300:9300
     environment:
       - discovery.type=single-node
       - xpack.security.enabled=false
       - xpack.security.enrollment.enabled=false
     mem_limit: 4g
     volumes:
       - ./elasticsearch/data:/usr/share/elasticsearch/data
       ####data folder must have chmod 777 and chown root:root (solo su data, non nelle cartelle interne)
     networks:
       - elastic-net

   kibana:
     image: docker.elastic.co/kibana/kibana:8.4.2
     restart: always
     ports:
       - 5601:5601
     environment:
       - ELASTICSEARCH_URL=http://elasticsearch:9200
     networks:
       - elastic-net
